<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Document;
use App\Models\Tag;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class DocumentSeeder extends Seeder
{
    public function run(): void
    {
        $adminId = User::where('email', 'admin@tts.com')->value('id');
        $coverImage = 'https://res.cloudinary.com/oceanmind/image/upload/v1777457291/logo_kgluuz.png';

        $cat = fn (string $name): int => Category::where('name', $name)->value('id')
            ?? throw new \RuntimeException("Category not found: {$name}");

        $tags = fn (array $slugs): array => Tag::whereIn('slug', $slugs)->pluck('id')->all();

        $documents = [
            // —— Lập trình Web (7) ——
            [
                'category_id' => $cat('Lập trình Web'),
                'title' => 'Lập trình Web với Laravel 10 từ cơ bản đến nâng cao',
                'description' => 'Framework Laravel 10 được dùng rộng rãi để xây dựng ứng dụng PHP có cấu trúc rõ ràng, bảo trì dễ dàng. Nội dung đi từ MVC, routing, middleware, Eloquent, validation đến queue, events và triển khai API thực tế. Phù hợp sinh viên năm cuối chuyên ngành CNTT và lập trình viên PHP cần hệ thống hóa kiến thức. Sau khóa học tự tay, người học có thể thiết kế module, viết test và tổ chức dự án theo chuẩn đội nhóm.',
                'author' => 'Nguyễn Văn Cường',
                'publisher' => 'NXB Thông tin và Truyền thông',
                'year' => 2023,
                'isbn' => '978-604-2041-18-2',
                'lang' => 'vi',
                'pages' => 452,
                'tags' => $tags(['laravel', 'php', 'web', 'database']),
            ],
            [
                'category_id' => $cat('Lập trình Web'),
                'title' => 'Vue.js 3 — Xây dựng ứng dụng SPA hiện đại',
                'description' => 'Vue 3 kết hợp Composition API và Vite giúp tách logic giao diện linh hoạt hơn so với phiên bản trước. Giáo trình hướng dẫn component, state, router, Pinia và tích hợp REST API an toàn. Đối tượng chính gồm frontend developer và fullstack muốn làm chủ SPA. Kết quả mong đợi là xây được ứng dụng một trang có cấu trúc thư mục chuẩn, tối ưu bundle và dễ mở rộng.',
                'author' => 'Trần Minh Phụng',
                'publisher' => 'NXB Đại học Quốc gia Hà Nội',
                'year' => 2022,
                'isbn' => '978-604-3188-72-4',
                'lang' => 'vi',
                'pages' => 380,
                'tags' => $tags(['vue', 'javascript', 'web', 'devops']),
            ],
            [
                'category_id' => $cat('Lập trình Web'),
                'title' => 'RESTful API Design với Laravel Sanctum',
                'description' => 'Xác thực token và phân quyền API là xương sống của ứng dụng web và mobile hiện đại. Sách trình bày thiết kế endpoint, versioning, throttling, CORS và bảo vệ brute-force kết hợp Sanctum. Phù hợp backend developer và kỹ sư cần chuẩn hóa API nội bộ hoặc SaaS. Người đọc nắm được luồng đăng nhập đa thiết bị, rotation token và kiểm thử Postman/Pest cho API.',
                'author' => 'Lê Hoàng Nam',
                'publisher' => 'NXB Khoa học và Kỹ thuật',
                'year' => 2023,
                'isbn' => '978-604-4472-05-9',
                'lang' => 'vi',
                'pages' => 296,
                'tags' => $tags(['laravel', 'php', 'security', 'web']),
            ],
            [
                'category_id' => $cat('Lập trình Web'),
                'title' => 'Fullstack JavaScript: Node.js + Vue.js',
                'description' => 'Một stack thống nhất ngôn ngữ giúp giảm chi phí chia sẻ kiểu dữ liệu và công cụ build giữa client và server. Tài liệu đề cập Express/Fastify, WebSocket, SSR cơ bản và pattern BFF khi ghép Vue. Hướng tới lập trình viên đã biết JavaScript muốn gói gọn dự án trong một repo monorepo. Bạn sẽ triển khai được luồng CRUD hoàn chỉnh, upload file và logging tập trung.',
                'author' => 'Phạm Đức Thịnh',
                'publisher' => 'Packt Publishing (bản dịch)',
                'year' => 2021,
                'isbn' => '978-604-5891-33-7',
                'lang' => 'vi',
                'pages' => 512,
                'tags' => $tags(['javascript', 'vue', 'web', 'network']),
            ],
            [
                'category_id' => $cat('Lập trình Web'),
                'title' => 'PHP 8.2 và lập trình hướng đối tượng',
                'description' => 'PHP 8.2 bổ sung readonly class, true type và cải thiện hiệu năng JIT ở nhiều workload. Phần OOP đi sâu về interface, trait, exception hierarchy và dependency injection thực dụng. Dành cho người mới chuyển từ thủ tục sang hướng đối tượng hoặc dev cần ôn nền tảng trước khi học framework. Nắm xong nội dung, bạn viết được class dễ test, tuân SOLID cơ bản và tránh anti-pattern thường gặp.',
                'author' => 'Hoàng Thế Vinh',
                'publisher' => 'NXB Lao động — Xã hội',
                'year' => 2023,
                'isbn' => '978-604-6720-44-1',
                'lang' => 'vi',
                'pages' => 340,
                'tags' => $tags(['php', 'laravel', 'algorithm', 'web']),
            ],
            [
                'category_id' => $cat('Lập trình Web'),
                'title' => 'Thiết kế giao diện với Tailwind CSS',
                'description' => 'Utility-first CSS giúp prototype nhanh mà vẫn kiểm soát được design token qua config. Cuốn hướng dẫn layout responsive, dark mode, component extract và tối giản CSS thừa với JIT. Lứa designer-developer lai hoặc team startup cần ship MV nhanh sẽ thấy hữu ích. Kỹ năng thu được gồm dựng dashboard, form phức tạp và đồng bộ với Vue/React không phá vỡ atomic class.',
                'author' => 'Đỗ Thu Hà',
                'publisher' => 'F8 Học lập trình (ản phẩm nội bộ chuyển sổ)',
                'year' => 2022,
                'isbn' => '978-604-7012-88-5',
                'lang' => 'vi',
                'pages' => 268,
                'tags' => $tags(['vue', 'javascript', 'web', 'mobile']),
            ],
            [
                'category_id' => $cat('Lập trình Web'),
                'title' => 'Docker cho lập trình viên Web',
                'description' => 'Container hóa môi trường dev giúp “chạy được trên máy tôi” không còn là câu chuyện may rủi. Từ Dockerfile multi-stage, Compose cho PHP-MySQL-Redis đến volume và debug trong container đều được minh họa. Dev web và DevOps junior muốn tự tin khi onboard dự án sẽ cần các chương này. Cuối sách bạn dựng stack Laravel/Vue song song, healthcheck service và pipeline build image nhẹ.',
                'author' => 'Vũ Quang Huy',
                'publisher' => 'NXB Công nghệ thông tin',
                'year' => 2024,
                'isbn' => '978-604-8156-11-3',
                'lang' => 'vi',
                'pages' => 312,
                'tags' => $tags(['docker', 'devops', 'linux', 'web']),
            ],

            // —— Trí tuệ nhân tạo (7) ——
            [
                'category_id' => $cat('Trí tuệ nhân tạo'),
                'title' => 'Trí tuệ nhân tạo — Cách tiếp cận hiện đại (bản dịch Russell & Norvig)',
                'description' => 'Bản dịch tóm lược các chủ đề tìm kiếm, học máy, suy luận và robot học từ giáo trình kinh điển. Mỗi phần có ví dụ trực quan giúp người mới hình dung không gian bài toán AI. Sinh viên ngành CNTT và kỹ sư dữ liệu muốn nền lý thuyết vững nên đọc trước khi đi sâu framework. Nội dung giúp bạn phân biệt symbolic AI và statistical learning, đồng thời đặt câu hỏi đạo đức khi triển khai.',
                'author' => 'Stuart Russell, Peter Norvig (dịch giả: Nhóm Khoa học Máy tính — ĐH Bách khoa)',
                'publisher' => 'NXB Giáo dục Việt Nam',
                'year' => 2020,
                'isbn' => '978-604-8330-22-7',
                'lang' => 'vi',
                'pages' => 620,
                'tags' => $tags(['ai', 'algorithm', 'machine-learning', 'data-science']),
            ],
            [
                'category_id' => $cat('Trí tuệ nhân tạo'),
                'title' => 'Machine Learning căn bản — Vũ Hữu Tiệp',
                'description' => 'Các mô hình học có giám sát và không giám sát được trình bày kèm ví dụ Python rút gọn. Trọng tâm là trực giác toán học thay vì chứng minh dài dòng, thuận tiến độ tự học. Người mới bước vào data science tại Việt Nam thường chọn quyển này làm sách đầu tay. Sau khi học, bạn triển khai pipeline tiền xử lý, huấn luyện và đánh giá model điển hình.',
                'author' => 'Vũ Hữu Tiệp',
                'publisher' => 'NXB Đại học Bách khoa Hà Nội',
                'year' => 2018,
                'isbn' => '978-604-9441-77-3',
                'lang' => 'vi',
                'pages' => 340,
                'tags' => $tags(['machine-learning', 'python', 'data-science', 'ai']),
            ],
            [
                'category_id' => $cat('Trí tuệ nhân tạo'),
                'title' => 'Deep Learning — Ian Goodfellow, Yoshua Bengio, Aaron Courville',
                'description' => 'Giáo trình nền tảng mạng neural, tối ưu, CNN, RNN và các chủ đề generative nâng cao. Phần lý thuyết gắn chặt với pseudocode và thực nghiệm để không rơi vào học vẹt. Nghiên cứu sinh và kỹ sư deep learning cần tra cứu khái niệm chuẩn nên giữ sách bên bàn làm việc. Bạn hiểu sâu hơn về vanishing gradient, regularization và cách đọc paper mới trong lĩnh vực.',
                'author' => 'Ian Goodfellow, Yoshua Bengio, Aaron Courville',
                'publisher' => 'MIT Press / bản dịch NXB Trẻ',
                'year' => 2016,
                'isbn' => '978-604-0550-81-9',
                'lang' => 'en',
                'pages' => 800,
                'tags' => $tags(['deep-learning', 'machine-learning', 'ai', 'algorithm']),
            ],
            [
                'category_id' => $cat('Trí tuệ nhân tạo'),
                'title' => 'Python cho Data Science và Machine Learning',
                'description' => 'Jupyter, NumPy, pandas và scikit-learn được dùng xuyên suốt qua bài toán dự báo và phân cụm. Chương cuối chạm nhẹ TensorFlow/Keras để người đọc chuyển tiếp deep learning. Data analyst muốn nâng cấp kỹ năng mô hình hóa tại doanh nghiệp sẽ thấy quỹ đạo rõ ràng. Kỹ năng thu được gồm làm sạch dữ liệu thực tế, feature engineering và trình bày metric cho stakeholder.',
                'author' => 'José Portilla (bản dịch)',
                'publisher' => 'NXB Thế giới',
                'year' => 2019,
                'isbn' => '978-604-1663-44-8',
                'lang' => 'vi',
                'pages' => 510,
                'tags' => $tags(['python', 'data-science', 'machine-learning', 'ai']),
            ],
            [
                'category_id' => $cat('Trí tuệ nhân tạo'),
                'title' => 'Neural Networks và Deep Learning — Giải thích trực quan',
                'description' => 'Hình minh họa từng bước lan truyền tiến và ngược giúp trực giác hóa khái niệm khó. Bài tập nhỏ với NumPy thuần trước khi dùng framework giúp củng cố đạo hàm ma trận. Sinh viên năm 3–4 ngành toán tin và dev chuyển ngành AI thường cần phần trực quan này. Bạn có thể tự cài một MLP mini, debug learning rate và nhận biết overfitting sớm.',
                'author' => 'Michael Nielsen (bản dịch tập thể)',
                'publisher' => 'Determination Press / NXB kết hợp',
                'year' => 2018,
                'isbn' => '978-604-2775-60-2',
                'lang' => 'vi',
                'pages' => 220,
                'tags' => $tags(['deep-learning', 'python', 'algorithm', 'machine-learning']),
            ],
            [
                'category_id' => $cat('Trí tuệ nhân tạo'),
                'title' => 'Xử lý ngôn ngữ tự nhiên (NLP) với Python',
                'description' => 'Từ tokenization, embedding đến transformer được giải thích trong bối cảnh pipeline xử lý văn bản tiếng Việt lẫn đa ngữ. Ví dụ thực hành phân loại ý kiến và tóm tắt văn bản ngắn. Kỹ sư xây chatbot nội bộ và product manager hiểu kỹ thuật nên đọc chương đánh giá. Người học biết lựa chọn mô hình pretrained, fine-tune an toàn dữ liệu và benchmark BLEU/ROUGE cơ bản.',
                'author' => 'Steven Bird, Ewan Klein, Edward Loper (bản lược Việt hóa)',
                'publisher' => 'NXB Khoa học Tự nhiên và Công nghệ',
                'year' => 2021,
                'isbn' => '978-604-3887-03-1',
                'lang' => 'vi',
                'pages' => 465,
                'tags' => $tags(['python', 'machine-learning', 'ai', 'data-science']),
            ],
            [
                'category_id' => $cat('Trí tuệ nhân tạo'),
                'title' => 'Computer Vision: Nhận dạng hình ảnh với TensorFlow',
                'description' => 'Kiến trúc CNN cổ điển và hiện đại được dùng để phân loại, phát hiện đối tượng và phân đoạn ảnh y tế mở đầu. Phần triển khai nhấn mạnh GPU, mixed precision và export model phục vụ edge nhẹ. Kỹ sư thị giác máy tính trong startup IoT và y tế sẽ có roadmap thực nghiệm. Bạn triển khai được luồng augment dữ liệu, metric IoU và kiểm thử độ lệch dataset.',
                'author' => 'Rajalingappaa Shanmugamani (bản dịch)',
                'publisher' => 'Packt / NXB Thông tin và Truyền thông',
                'year' => 2020,
                'isbn' => '978-604-4990-12-6',
                'lang' => 'vi',
                'pages' => 540,
                'tags' => $tags(['deep-learning', 'machine-learning', 'ai', 'python']),
            ],

            // —— Tài chính (7) ——
            [
                'category_id' => $cat('Tài chính'),
                'title' => 'Phân tích tài chính doanh nghiệp — Nguyễn Minh Kiều',
                'description' => 'Chỉ số thanh khoản, đòn bẩy và hiệu quả sử dụng tài sản được phân tích qua báo cáo mẫu ngành sản xuất — dịch vụ. Phần bài tập hướng tới đọc nhanh chứng từ và nhận diện gian lận cơ bản. Sinh viên tài chính ngân hàng và CFO khởi đầu nghề cần khung tư duy hệ thống. Người học diễn giải được biến động dòng tiền và kết nối số liệu với chiến lược vốn.',
                'author' => 'Nguyễn Minh Kiều',
                'publisher' => 'NXB Thống kê',
                'year' => 2018,
                'isbn' => '978-604-1998-14-5',
                'lang' => 'vi',
                'pages' => 392,
                'tags' => $tags(['finance', 'algorithm', 'database', 'marketing']),
            ],
            [
                'category_id' => $cat('Tài chính'),
                'title' => 'Quản trị tài chính — Nguyễn Văn Thuận',
                'description' => 'Ra quyết định đầu tư dự án và cấu trúc vốn được minh họa bằng NPV, WACC và kịch bản nhạy cảm. Vai trò của thị trường vốn Việt Nam được cập nhật theo vòng pháp lý gần nhất. Giảng viên và học viên MBA muốn bài tập sát doanh nghiệp nội địa sẽ nhắm tới tác phẩm này. Sau khóa, bạn lập được mô hình tài chính spreadsheet có kiểm soát lỗi và trình bày board ngắn gọn.',
                'author' => 'Nguyễn Văn Thuận',
                'publisher' => 'NXB Đại học Kinh tế Quốc dân',
                'year' => 2020,
                'isbn' => '978-604-2110-66-2',
                'lang' => 'vi',
                'pages' => 448,
                'tags' => $tags(['finance', 'marketing', 'cloud', 'security']),
            ],
            [
                'category_id' => $cat('Tài chính'),
                'title' => 'Đầu tư chứng khoán cho người mới bắt đầu',
                'description' => 'Cơ chế sàn, lệnh và quản trị danh mục đơn giản giúp người mới không bị choáng bởi biến động ngắn hạn. Không khuyến nghị cụ thể mã cổ phiếu mà tập trung nguyên tắc đa dạng hóa và kỷ luật vốn. Nhà đầu tư cá nhân và sinh viên tài chính cá nhân cần nền đạo đức giao dịch. Bạn hiểu được khác biệt đầu tư và đầu cơ, đọc báo cáo ngắn và đặt stop hợp lý theo mục tiêu.',
                'author' => 'Trần Thị Thu Hằng',
                'publisher' => 'NXB Tài chính',
                'year' => 2021,
                'isbn' => '978-604-3222-90-8',
                'lang' => 'vi',
                'pages' => 260,
                'tags' => $tags(['finance', 'marketing', 'blockchain', 'security']),
            ],
            [
                'category_id' => $cat('Tài chính'),
                'title' => 'Kế toán tài chính theo chuẩn mực Việt Nam',
                'description' => 'Chuẩn mực ghi nhận doanh thu, dự phòng và báo cáo hợp nhất được đối chiếu ví dụ điển hình. Phần bài tập drill tài khoản giúp thói quen kiểm tra chéo số liệu. Kế toán viên DN và sinh viên chuẩn bị chứng chỉ hành nghề cần sổ tay này. Người học lập được bút toán điều chỉnh cuối kỳ và giải thích chênh lệch với kiểm toán nội bộ.',
                'author' => 'PGS.TS. Phạm Văn Dũng',
                'publisher' => 'NXB Tài chính Kế toán',
                'year' => 2022,
                'isbn' => '978-604-4335-22-4',
                'lang' => 'vi',
                'pages' => 520,
                'tags' => $tags(['finance', 'database', 'algorithm', 'security']),
            ],
            [
                'category_id' => $cat('Tài chính'),
                'title' => 'Tài chính hành vi: Tâm lý đầu tư',
                'description' => 'Thiên kiến xác nhận, nỗi sợ mất mát và hiệu ứng đám đông ảnh hưởng quyết định danh mục cá nhân. Nghiên cứu thực nghiệm được tóm lược để người đọc tự nhận diện pattern của chính mình. Cố vấn tài chính và nhà báo kinh tế viết về thị trường nên tham khảo. Bạn xây checklist trước khi mua bán, ghi nhật ký cảm xúc và phân tích ngược giao dịch sai sót.',
                'author' => 'Richard H. Thaler (bản dịch)',
                'publisher' => 'NXB Trẻ',
                'year' => 2017,
                'isbn' => '978-604-4446-33-7',
                'lang' => 'vi',
                'pages' => 368,
                'tags' => $tags(['finance', 'marketing', 'machine-learning', 'ai']),
            ],
            [
                'category_id' => $cat('Tài chính'),
                'title' => 'Phân tích đầu tư và quản lý danh mục',
                'description' => 'Mô hình Markowitz, CAPM đơn giản và phương pháp xếp hạng ETF được trình bày bằng bảng tính minh họa. Nhắm tới nhà quản lý quỹ mô phỏng nhỏ và tác nghiệp phòng nghiên cứu. Sinh viên chương trình quốc tế CFA Level I phần portfolio cần ôn tập căn bản. Kết quả là bạn giải thích được đường hiệu quả, đo beta thực nghiệm và hiểu giới hạn mô hình.',
                'author' => 'Reilly, Brown (tuyển dịch)',
                'publisher' => 'NXB Thế giới',
                'year' => 2019,
                'isbn' => '978-604-4558-44-0',
                'lang' => 'vi',
                'pages' => 600,
                'tags' => $tags(['finance', 'algorithm', 'data-science', 'marketing']),
            ],
            [
                'category_id' => $cat('Tài chính'),
                'title' => 'Nguyên lý tài chính — Brealey & Myers',
                'description' => 'Giáo trình cổ điển về định giá, cấu trúc vốn và chính sách cổ tức phục vụ chương trình đại học tiếng Anh. Bản dịch lược bỏ một phần bài tập nặng để tập trung khái niệm lõi. Học viên chương trình liên kết và giảng viên muốn slide bổ trợ nhanh sẽ dùng tài liệu này. Người đọc nắm được lý thuyết MM có thuế, tùy chọn thực và liên hệ thị trường mới nổi.',
                'author' => 'Richard A. Brealey, Stewart C. Myers',
                'publisher' => 'McGraw-Hill (bản dịch)',
                'year' => 2015,
                'isbn' => '978-604-5669-55-3',
                'lang' => 'en',
                'pages' => 1024,
                'tags' => $tags(['finance', 'marketing', 'english', 'algorithm']),
            ],

            // —— Marketing (7) ——
            [
                'category_id' => $cat('Marketing'),
                'title' => 'Marketing căn bản — Philip Kotler',
                'description' => 'Bốn yếu tố marketing mix và hành trình khách hàng được cập nhật ví dụ thương hiệu toàn cầu lẫn địa phương. Các chương nhấn mạnh đo lường ROI và đạo đức quảng cáo. Sinh viên ngành QTKD và marketer junior cần nền tảng hệ thống. Người học phác thảo persona, chiến lược định vị và kế hoạch truyền thông theo mục tiêu doanh thu.',
                'author' => 'Philip Kotler, Gary Armstrong (bản dịch)',
                'publisher' => 'Pearson (bản dịch)',
                'year' => 2016,
                'isbn' => '978-604-9062-18-0',
                'lang' => 'vi',
                'pages' => 620,
                'tags' => $tags(['marketing', 'finance', 'english', 'web']),
            ],
            [
                'category_id' => $cat('Marketing'),
                'title' => 'Digital Marketing toàn tập',
                'description' => 'Kênh owned, earned và paid media được gắn vào funnel từ nhận biết đến chuyển đổi. Phần thực hành gồm lập content calendar, phân bổ ngân sách quảng cáo và đọc dashboard cơ bản. Marketer làm việc trong SMB và agency nhỏ thường cần bản đồ tổng hợp như vậy. Kết quả là bạn triển khai chiến dịch đa kênh có KPI rõ, tránh chạy rời rạc không đo được.',
                'author' => 'Đào Minh Tuấn',
                'publisher' => 'NXB Công thương',
                'year' => 2022,
                'isbn' => '978-604-1903-44-1',
                'lang' => 'vi',
                'pages' => 412,
                'tags' => $tags(['marketing', 'web', 'database', 'ai']),
            ],
            [
                'category_id' => $cat('Marketing'),
                'title' => 'Content Marketing: Chiến lược tạo nội dung',
                'description' => 'Insight khách hàng và editorial guideline giúp nội dung không trôi theo trend vô nghĩa. Sách đi sâu storytelling, SEO nội dung dài hơi và tái sử dụng asset đa định dạng. Trưởng nhóm content và founder dịch vụ B2B muốn lead ổn định sẽ áp dụng được. Sau khóa, bạn lập được matrix chủ đề, ma trận CTA và quy trình duyệt bản thảo.',
                'author' => 'Nguyễn Thị Thu Hà',
                'publisher' => 'NXB Trẻ',
                'year' => 2021,
                'isbn' => '978-604-2014-55-2',
                'lang' => 'vi',
                'pages' => 308,
                'tags' => $tags(['marketing', 'web', 'english', 'mobile']),
            ],
            [
                'category_id' => $cat('Marketing'),
                'title' => 'SEO: Tối ưu hóa công cụ tìm kiếm',
                'description' => 'Crawl budget, internal link và E-E-A-T được diễn giải song song với technical audit đơn giản. Hướng dẫn tránh dark-hat và xây dựng cấu trúc URL bền vững theo năm. Chuyên viên growth và dev có SEO hybrid trong startup sẽ thấy lộ trình kiểm tra. Người học biết đọc Search Console, ưu tiên mục có tiềm năng traffic và theo dõi cannibalization.',
                'author' => 'Eric Enge (tuyển dịch)',
                'publisher' => "O'Reilly (bản dịch)",
                'year' => 2018,
                'isbn' => '978-604-2125-66-3',
                'lang' => 'vi',
                'pages' => 476,
                'tags' => $tags(['marketing', 'web', 'database', 'algorithm']),
            ],
            [
                'category_id' => $cat('Marketing'),
                'title' => 'Xây dựng thương hiệu trong kỷ nguyên số',
                'description' => 'Brand purpose và trải nghiệm omnichannel cần thống nhất giữa online và điểm chạm vật lý. Case thương hiệu Việt và khu vực giúp minh họa chi phí đổi nhận diện. Giám đốc marketing và designer chiến lược làm việc cùng nhau nên đọc chung. Bạn có khung đo độ nhớ, net promoter và kế hoạch khủng hoảng truyền thông.',
                'author' => 'David Aaker (bản dịch)',
                'publisher' => 'NXB Thế giới',
                'year' => 2019,
                'isbn' => '978-604-2236-77-4',
                'lang' => 'vi',
                'pages' => 356,
                'tags' => $tags(['marketing', 'finance', 'mobile', 'web']),
            ],
            [
                'category_id' => $cat('Marketing'),
                'title' => 'Marketing trên mạng xã hội',
                'description' => 'Thuật toán feed và định dạng video ngắn đòi hỏi chiến lược sáng tạo khác biệt từng nền tảng. Phần đo lường chuyển đổi từ UTM đến pixel (trong giới hạn quyền riêng tư) được trình bày cẩn trọng. Community manager và KOL coordinator cần playbook xử lý comment tiêu cực. Hoàn thành, bạn lên lịch đăng cân bằng, thử nghiệm creative và tối ưu chi phí mỗi lead.',
                'author' => 'Phạm Khánh Linh',
                'publisher' => 'NXB Thông tin và Truyền thông',
                'year' => 2023,
                'isbn' => '978-604-2347-88-5',
                'lang' => 'vi',
                'pages' => 264,
                'tags' => $tags(['marketing', 'web', 'mobile', 'ai']),
            ],
            [
                'category_id' => $cat('Marketing'),
                'title' => 'Email Marketing hiệu quả',
                'description' => 'Phân đoạn list, trigger automation và thiết kế subject line được kiểm chứng qua thử nghiệm nhỏ. Nhắc rõ GDPR/Vietnam laws về thu thập địa chỉ để tránh rủi ro pháp lý. Chuyên viên CRM và founder ecommerce sẽ cần quy trình unsubscribe rõ ràng. Người đọc xây journey nhỏ, đánh giá open/click thật và tránh spam folder.',
                'author' => 'Chad S. White (tuyển dịch)',
                'publisher' => 'NXB Hồng Đức',
                'year' => 2020,
                'isbn' => '978-604-2458-99-6',
                'lang' => 'vi',
                'pages' => 292,
                'tags' => $tags(['marketing', 'web', 'database', 'security']),
            ],

            // —— Tiếng Anh (7) ——
            [
                'category_id' => $cat('Tiếng Anh'),
                'title' => 'English Grammar in Use — Raymond Murphy',
                'description' => 'Intermediate grammar topics are grouped into short units with facing practice exercises so learners can check understanding immediately. Clear tables contrast easily confused structures such as present perfect versus past simple. Self-study adults and classroom teachers who want a reliable syllabus gravitate toward this Cambridge classic. By working through the book, you gain confidence producing accurate spoken and written English in everyday contexts.',
                'author' => 'Raymond Murphy',
                'publisher' => 'Cambridge University Press',
                'year' => 2019,
                'isbn' => '978-604-2569-00-7',
                'lang' => 'en',
                'pages' => 380,
                'tags' => $tags(['english', 'ielts', 'web', 'marketing']),
            ],
            [
                'category_id' => $cat('Tiếng Anh'),
                'title' => 'IELTS Academic — Hướng dẫn toàn diện',
                'description' => 'Cấu trúc bài thi Reading, Listening, Writing Task 1–2 và Speaking band descriptor được phân tích bằng ví dụ điểm 6–8. Chiến lược quản lý thời gian và paraphrase an toàn giúp tránh lặp nguyên đề bài. Thí sinh ôn IELTS Academic trong 2–4 tháng và giáo viên trung tâm thường chọn giáo trình hệ thống. Người học có checklist tự chấm writing và bộ chủ đề speaking lặp lại được.',
                'author' => 'Pauline Cullen (biên tập bản dịch)',
                'publisher' => 'NXB Đại học Sư phạm',
                'year' => 2021,
                'isbn' => '978-604-2670-11-8',
                'lang' => 'vi',
                'pages' => 520,
                'tags' => $tags(['ielts', 'english', 'marketing', 'web']),
            ],
            [
                'category_id' => $cat('Tiếng Anh'),
                'title' => 'Business English for Professionals',
                'description' => 'Meetings, negotiation phrases, and email tone are taught through realistic dialogues between international teams. Cultural notes highlight direct versus indirect styles so learners avoid sounding rude or vague. Mid-career engineers, accountants, and project managers working in foreign firms will find the scenarios familiar. You finish able to chair a short stand-up, summarize action items, and follow up politely in writing.',
                'author' => 'James Schofield',
                'publisher' => 'Macmillan Education',
                'year' => 2017,
                'isbn' => '978-604-2781-22-9',
                'lang' => 'en',
                'pages' => 240,
                'tags' => $tags(['english', 'marketing', 'finance', 'mobile']),
            ],
            [
                'category_id' => $cat('Tiếng Anh'),
                'title' => 'Từ vựng tiếng Anh theo chủ đề',
                'description' => 'Từ vựng được nhóm theo chủ đề đời sống, học thuật và công sở kèm ví dụ câu đủ ngữ cảnh. Kỹ thuật flashcard spaced repetition được gợi ý để nhớ lâu thay vì học vẹt danh sách. Sinh viên ĐH khối xã hội và người đi làm cần vốn từ thực dụng sẽ có lộ trình 60 chủ đề. Sau sách, bạn chủ động ghép collocation vào speaking, giảm dịch word-by-word trong đầu.',
                'author' => 'Hoàng Thùy Linh',
                'publisher' => 'NXB Trẻ',
                'year' => 2020,
                'isbn' => '978-604-2892-33-0',
                'lang' => 'vi',
                'pages' => 340,
                'tags' => $tags(['english', 'ielts', 'algorithm', 'database']),
            ],
            [
                'category_id' => $cat('Tiếng Anh'),
                'title' => 'Academic Writing Skills',
                'description' => 'Paragraph skeleton, hedging language, and citation styles are explained with before-and-after student samples. Exercises target coherence so reviewers do not lose the thread of your argument. International master students and young researchers publishing in English need these conventions early. Completing the tasks helps you outline faster, integrate sources without plagiarism risk, and self-edit for clarity.',
                'author' => 'John Sampson',
                'publisher' => 'Palgrave Study Skills',
                'year' => 2018,
                'isbn' => '978-604-2903-44-1',
                'lang' => 'en',
                'pages' => 288,
                'tags' => $tags(['english', 'ielts', 'web', 'security']),
            ],
            [
                'category_id' => $cat('Tiếng Anh'),
                'title' => 'TOEIC 900+ — Chiến lược luyện thi',
                'description' => 'Part 5–7 tập trung nhận diện trap lexical và skimming đoạn văn theo nhóm câu hỏi. Audio tốc độ tăng dần giúp quen giọng Mỹ, Anh và Úc thường xuất hiện trong đề thi doanh nghiệp. Nhân viên văn phòng và sinh viên năm cuối chuẩn bị chứng chỉ quy định TOEIC sẽ có kế hoạch 8 tuần. Bạn theo dõi lỗi lặp lại, xây ngân hàng phrase và kiểm soát stress phòng thi.',
                'author' => 'Lê Phương Thảo',
                'publisher' => 'NXB Đại học Quốc gia Hà Nội',
                'year' => 2022,
                'isbn' => '978-604-3014-55-2',
                'lang' => 'vi',
                'pages' => 360,
                'tags' => $tags(['english', 'marketing', 'mobile', 'network']),
            ],
            [
                'category_id' => $cat('Tiếng Anh'),
                'title' => 'Pronunciation Practice — American English',
                'description' => 'Stress, linking, and weak forms in American accent are drilled with minimal pairs and shadowing audio. Visual mouth diagrams support learners whose first language syllable timing differs greatly from English. Actors, tour guides, and call-center trainees who must sound natural on phone benefit from the structure. After practice, you monitor your intonation, reduce intrusive final consonants, and present with clearer focus words.',
                'author' => 'Ann Cook',
                'publisher' => 'Barron\'s Educational Series',
                'year' => 2016,
                'isbn' => '978-604-3125-66-3',
                'lang' => 'en',
                'pages' => 198,
                'tags' => $tags(['english', 'ielts', 'web', 'mobile']),
            ],

            // —— Tiếng Hàn (7) ——
            [
                'category_id' => $cat('Tiếng Hàn'),
                'title' => 'Tiếng Hàn tổng hợp — Sơ cấp 1',
                'description' => 'Hangul, phụ âm cuối và phép ghép âm tiết được luyện qua bài hội thoại gia đình và campus đơn giản. Ngữ pháp nhập môn trình bày song song tiếng Việt để tránh hiểu sai thứ tự động từ. Người mới học tiếng Hàn cho du học hoặc làm việc với đối tác Hàn Quốc khởi đầu từ quyển này. Kết thúc cấp độ, bạn đọc chậm truyện ngắn, viết câu hiện tại quá khứ cơ bản và nắm nghi thức xưng hô.',
                'author' => 'Trường ĐH Ngoại ngữ Hà Nội (biên soạn)',
                'publisher' => 'NXB Đại học Quốc gia Hà Nội',
                'year' => 2019,
                'isbn' => '978-604-3347-88-5',
                'lang' => 'vi',
                'pages' => 280,
                'tags' => $tags(['english', 'mobile', 'web', 'marketing']),
            ],
            [
                'category_id' => $cat('Tiếng Hàn'),
                'title' => 'Tiếng Hàn tổng hợp — Sơ cấp 2',
                'description' => 'Mẫu câu trung cấp sơ giản về công việc, mua sắm và chỉ đường được luyện nghe hiểu tốc độ chậm trung bình. Bài đọc kéo dài hơn cấp 1 để làm quen với hậu tố tôn kính sơ bộ. Học viên đã xong sơ cấp 1 và chuẩn bị TOPIK I sẽ thấy bước chuyển hợp lý. Người học tăng vốn từ chủ đề thường ngày, tự ghi chú pattern và luyện phát âm phản xạ.',
                'author' => 'Trường ĐH Ngoại ngữ Hà Nội (biên soạn)',
                'publisher' => 'NXB Đại học Quốc gia Hà Nội',
                'year' => 2019,
                'isbn' => '978-604-3458-99-6',
                'lang' => 'vi',
                'pages' => 300,
                'tags' => $tags(['english', 'ielts', 'web', 'mobile']),
            ],
            [
                'category_id' => $cat('Tiếng Hàn'),
                'title' => 'Ngữ pháp tiếng Hàn thực hành',
                'description' => 'Cấu trúc động từ, bổ ngữ và mệnh đề phụ hay gặp trong văn nói được phân loại bảng tra cứu. Mỗi mục kèm drill biến đổi câu và lỗi sinh viên Việt thường mắc. Sinh năm hai chuyên ngữ Hàn và người tự học nâng cao cần sổ tay ngắn gọn. Sau khi ôn, bạn phân biệt được 어려요/았어요, lựa chọn trợ từ phù hợp trong câu ghép.',
                'author' => 'Kim Soo-young (biên dịch: Nguyễn Văn Hải)',
                'publisher' => 'NXB Đại học Quốc gia TP. HCM',
                'year' => 2021,
                'isbn' => '978-604-3569-01-7',
                'lang' => 'vi',
                'pages' => 356,
                'tags' => $tags(['english', 'algorithm', 'database', 'web']),
            ],
            [
                'category_id' => $cat('Tiếng Hàn'),
                'title' => 'TOPIK I — Luyện thi cấp độ 1–2',
                'description' => 'Đề mẫu listening/reading và phần viết ngắn TOPIK I được phân tích chiến lược làm bài trong thời gian giới hạn. Bảng từ vựng tần suất cao trong đề thi tập trung chủ đề sinh hoạt, công sở sơ đẳng. Người lao động chuẩn bị chứng chỉ cho chương trình EPS hoặc du học dự bị cần lộ trình 10 tuần. Bạn tự chấm điểm, ghi nhật ký lỗi nghe trượt và lặp lại đoạn hội thoại gốc Hàn.',
                'author' => 'Park Ji-eun (biên tập nội địa hóa)',
                'publisher' => 'NXB Hồng Đức',
                'year' => 2020,
                'isbn' => '978-604-3670-12-8',
                'lang' => 'vi',
                'pages' => 248,
                'tags' => $tags(['ielts', 'english', 'marketing', 'mobile']),
            ],
            [
                'category_id' => $cat('Tiếng Hàn'),
                'title' => 'Hội thoại tiếng Hàn thường ngày',
                'description' => 'Các tình huống chợ, nhà hàng, bưu điện và phòng khám được dựng thành hội thoại song ngữ có phiên âm Latinh. Ghi chú văn hóa nhấn mạnh thái độ lịch sự khi xin giúp đỡ, cảm ơn. Du khách và người học giao tiếp cấp tốc trước chuyến đi Hàn sẽ mang sách dễ tra. Hoàn thành, bạn nói được chunk cố định tự tin, bắt nhịp tốc độ người bản xứ trong cửa hàng thực tế.',
                'author' => 'Choi Mi-kyung (tuyển dịch)',
                'publisher' => 'NXB Thế giới',
                'year' => 2018,
                'isbn' => '978-604-3781-23-9',
                'lang' => 'vi',
                'pages' => 196,
                'tags' => $tags(['english', 'web', 'mobile', 'marketing']),
            ],
            [
                'category_id' => $cat('Tiếng Hàn'),
                'title' => 'Tiếng Hàn cho giao tiếp văn phòng',
                'description' => 'Email công sở, cuộc họp online và báo cáo ngắn bằng tiếng Hàn trung cấp sơ được viết theo template an toàn. Phần honorific giới thiệu mức độ lịch sự khi nói với cấp trên đầu tiên. Nhân viên DN Việt làm việc với HQ Hàn cần chuẩn hóa cách xưng hô. Bạn soạn được lịch họp, xin nghỉ phép ngắn và tóm tắt công việc hàng tuần bằng văn bản lịch sự.',
                'author' => 'Han Jong-su (biên tập nhóm dự án)',
                'publisher' => 'NXB Lao động',
                'year' => 2023,
                'isbn' => '978-604-3892-34-0',
                'lang' => 'vi',
                'pages' => 272,
                'tags' => $tags(['english', 'finance', 'marketing', 'web']),
            ],
            [
                'category_id' => $cat('Tiếng Hàn'),
                'title' => 'Đọc hiểu tiếng Hàn trung cấp',
                'description' => 'Bài báo ngắn, poster sự kiện và bảng thông báo công cộng rèn kĩ năng nhận thông tin nhanh chính xác. Câu hỏi suy luận nhẹ giúp chuyển từ đọc từng từ sang đọc theo cụm. Sinh viên năm 3 chuyên Hàn và người ôn TOPIK II mức 3–4 sẽ cần nguồn đọc có chú giải. Đọc xong, bạn tóm tắt 3 ý chính, nhận biết quảng cáo ẩn và tra nhanh từ chuyên ngành nhẹ.',
                'author' => 'Lee Young-ae (tuyển bài dịch)',
                'publisher' => 'NXB Đại học Huế',
                'year' => 2022,
                'isbn' => '978-604-3903-45-1',
                'lang' => 'vi',
                'pages' => 318,
                'tags' => $tags(['english', 'database', 'algorithm', 'web']),
            ],

            // —— Vật lý (7) ——
            [
                'category_id' => $cat('Vật lý'),
                'title' => 'Đại cương vật lý đại học — Lương Duyên Bình',
                'description' => 'Cơ học, nhiệt, điện và sóng nhập môn được trình bày tuần tự với ví dụ định lượng gần đời sống. Bài tập cuối chương nhấn mạnh ước lượng bậc thứ và kiểm tra đơn vị SI. Sinh viên CNTT, y dược và kinh tế lấy tín chỉ vật lý đại cương dùng sách làm chuẩn. Người học củng cố tư duy mô hình hóa, đọc đồ thị thực nghiệm và trình bày lời giải có chiều sâu.',
                'author' => 'Lương Duyên Bình',
                'publisher' => 'NXB Giáo dục Việt Nam',
                'year' => 2017,
                'isbn' => '978-604-4015-56-2',
                'lang' => 'vi',
                'pages' => 440,
                'tags' => $tags(['algorithm', 'database', 'english', 'ai']),
            ],
            [
                'category_id' => $cat('Vật lý'),
                'title' => 'Cơ học Newton và ứng dụng kỹ thuật',
                'description' => 'Định luật Newton, động lượng và moment lực được áp dụng lên pulley, va chạm và cửa quay kỹ thuật. Phần mô phỏng số mở đầu giúp sinh viên so sánh lý thuyết với dữ liệu logger nhỏ. Kỹ sư cơ khí năm đầu và học sinh chuyên lý thi HSG cần bài tập đa dạng độ khó. Sau khóa, bạn chọn hệ qui chiếu phù hợp, phân tích lực ma sát và ước lượng nhanh an toàn kết cấu tĩnh học.',
                'author' => 'Nguyễn Hữu Cảnh',
                'publisher' => 'NXB Đại học Bách khoa Hà Nội',
                'year' => 2019,
                'isbn' => '978-604-4126-67-3',
                'lang' => 'vi',
                'pages' => 360,
                'tags' => $tags(['algorithm', 'machine-learning', 'database', 'english']),
            ],
            [
                'category_id' => $cat('Vật lý'),
                'title' => 'Điện học và từ trường',
                'description' => 'Định luật Gauss, Ampère và Faraday giải thích xuyên suốt tụ điện, cuộn dây và máy biến áp lý tưởng. Ví dụ tính toán tránh nhảy thẳng vào vector phức trước khi nắm mạch DC. Sinh viên điện — điện tử và năng lượng tái tạo cần nền Maxwell trực giác. Bạn đọc được sơ đồ mạch từ thông, ước lượng tổn hao nhỏ và liên hệ với ứng dụng thực tế như RFID.',
                'author' => 'David J. Griffiths (tuyển chương bản dịch)',
                'publisher' => 'Pearson (bản dịch)',
                'year' => 2016,
                'isbn' => '978-604-4237-78-4',
                'lang' => 'vi',
                'pages' => 520,
                'tags' => $tags(['algorithm', 'network', 'database', 'linux']),
            ],
            [
                'category_id' => $cat('Vật lý'),
                'title' => 'Vật lý hiện đại: Thuyết tương đối hẹp',
                'description' => 'Biến đổi Lorentz, đồng thời và thế năng — động lượng relativistic được minh họa bài toán tàu và đồng hồ ánh sáng. Mục tiêu không phải chứng minh đầy đủ tensor mà giúp người đọc tin vào dự đoán đo được. Sinh viên vật lý năm 2 và kỹ sư viễn thông hiếu kỳ GPS học để hiểu hiệu chỉnh thời gian. Bạn tính được time dilation đơn giản và trình bày mâu thuẫn song song cổ điển.',
                'author' => 'TS. Trần Ngọc Anh',
                'publisher' => 'NXB Khoa học và Kỹ thuật',
                'year' => 2020,
                'isbn' => '978-604-4348-89-5',
                'lang' => 'vi',
                'pages' => 240,
                'tags' => $tags(['algorithm', 'ai', 'database', 'english']),
            ],
            [
                'category_id' => $cat('Vật lý'),
                'title' => 'Dao động và sóng cơ',
                'description' => 'Phương trình dao động điều hòa, sóng dừng trên dây và vận tốc âm thanh trong môi trường khác nhau được thử nghiệm nhạc cụ đơn giản. Bài lab hướng dẫn đo tần số cộng hưởng với phần mềm miễn phí. Giáo viên THPT chuyên và sinh viên sư phạm lý cần hoạt động thực hành sát thực tế. Người học thiết kế được bộ thí nghiệm mini, giải thích hiệu ứng Doppler đời sống và trình bày sai số đo.',
                'author' => 'Nguyễn Thị Hương Giang',
                'publisher' => 'NXB Đại học Sư phạm',
                'year' => 2018,
                'isbn' => '978-604-4459-90-6',
                'lang' => 'vi',
                'pages' => 310,
                'tags' => $tags(['algorithm', 'database', 'english', 'web']),
            ],
            [
                'category_id' => $cat('Vật lý'),
                'title' => 'Quang học sóng',
                'description' => 'Giao thoa, nhiễu xạ và phân cực được trình bày bằng thí nghiệm Young, khe đơn và film phân cực. Liên hệ ứng dụng camera, laser pointer an toàn và hiển thị LCD cập nhật gần đây. Sinh viên quang điện tử năm đầu và photographer khoa học cần nền sóng vững trước khi học trừu tượng hơn. Bạn ước lượng bước sóng từ khe, hiểu độ phân giải giới hạn và đọc đồ thị cường độ.',
                'author' => 'Eugene Hecht (tuyển dịch)',
                'publisher' => 'NXB Trẻ',
                'year' => 2015,
                'isbn' => '978-604-4560-01-7',
                'lang' => 'vi',
                'pages' => 680,
                'tags' => $tags(['algorithm', 'machine-learning', 'database', 'ai']),
            ],
            [
                'category_id' => $cat('Vật lý'),
                'title' => 'Nhiệt học và vật lý thống kê cơ bản',
                'description' => 'Định luật nhiệt động học, entropy và phân bố Maxwell–Boltzmann mở đường cho hiểu máy nhiệt và dao động phân tử. Ví dụ piston, khí lý tưởng và cycle Carnot giúp trực giác trước khi đọc công thức vi phân. Kỹ sư hóa, năng lượng và sinh viên vật lý vật chất ngưng tụ năm đầu thường dùng làm ôn tập. Bạn tính hiệu suất chu trình đơn giản, giải thích tại sao nhiệt độ tuyệt đối là giới hạn và liên hệ phản ứng hóa học tỏa nhiệt.',
                'author' => 'Charles Kittel (tuyển chương bản dịch)',
                'publisher' => 'NXB Thế giới',
                'year' => 2017,
                'isbn' => '978-604-4671-12-8',
                'lang' => 'vi',
                'pages' => 420,
                'tags' => $tags(['algorithm', 'database', 'data-science', 'english']),
            ],

            // —— Hóa học (7) ——
            [
                'category_id' => $cat('Hóa học'),
                'title' => 'Hóa đại cương — Đặng Đình Rức',
                'description' => 'Cấu tạo nguyên tử, bảng tuần hoàn và liên kết hóa học được ôn hệ thống trước phần động học phản ứng cơ bản. Bài tập định lượng nồng nhằm vào sinh viên y dược và công nghệ thực phẩm. Giảng viên đại cương và học sinh ôn thi đại học khối A cần nguồn bài tập đa dạng. Người học cân bằng phản ứng điện hóa, đọc biểu đồ năng lượng đơn giản và liên hệ thực tiễn xử lý nước.',
                'author' => 'Đặng Đình Rức',
                'publisher' => 'NXB Giáo dục Việt Nam',
                'year' => 2016,
                'isbn' => '978-604-4782-23-9',
                'lang' => 'vi',
                'pages' => 540,
                'tags' => $tags(['database', 'algorithm', 'linux', 'english']),
            ],
            [
                'category_id' => $cat('Hóa học'),
                'title' => 'Hóa hữu cơ căn bản',
                'description' => 'Danh pháp IUPAC, cơ chế SN1/SN2 và phản ứng của ancol — axit cacboxylic được minh họa scheme electron mũi tên. Phần lab an toàn nhấn mạnh hood, găng và xử lý dung môi dễ cháy. Sinh viên dược và hóa dược năm đầu cần nền cơ chế để sau này học tổng hợp thuốc. Sau sách, bạn vẽ được đồng phân, dự đoán sản phẩm thay thế electrophile và đọc phổ IR cơ bản.',
                'author' => 'Paula Yurkanis Bruice (tuyển dịch)',
                'publisher' => 'Pearson (bản dịch)',
                'year' => 2018,
                'isbn' => '978-604-4893-34-0',
                'lang' => 'vi',
                'pages' => 712,
                'tags' => $tags(['database', 'algorithm', 'ai', 'machine-learning']),
            ],
            [
                'category_id' => $cat('Hóa học'),
                'title' => 'Hóa phân tích thực hành',
                'description' => 'Chuẩn độ acid — base, phức chất và phân tích quang phổ UV-Vis phục vụ kiểm định mẫu môi trường. Quy trình ghi sổ thí nghiệm GLP đơn giản giúp trace lại lỗi serie đo. Chuyên viên QC nhà máy thực phẩm và nước sinh hoạt áp dụng trực tiếp checklist. Bạn tự tính không độ tin cậy lặp lại, chọn chỉ thị phù hợp và tránh nhiễm chéo mẫu.',
                'author' => 'Gary D. Christian (tuyển chương bản dịch)',
                'publisher' => 'NXB Khoa học và Kỹ thuật',
                'year' => 2019,
                'isbn' => '978-604-5904-45-1',
                'lang' => 'vi',
                'pages' => 380,
                'tags' => $tags(['database', 'algorithm', 'linux', 'security']),
            ],
            [
                'category_id' => $cat('Hóa học'),
                'title' => 'Hóa lý và động học phản ứng',
                'description' => 'Phương trình Arrhenius, cân bằng hóa học và động học phức được gắn với thí nghiệm học máy đơn giản phòng lab sinh viên. Hoạt động nhóm thiết kế phản ứng phụ thuộc nhiệt độ để hiểu Le Chatelier. Ngành kỹ thuật hóa và vật liệu polyme cần nền hóa lý trước mô phỏng phản ứng lớn. Người đọc ước tính hằng số tốc độ, đọc biểu đồ Eyring và bàn luận vai trò xúc tác.',
                'author' => 'Peter W. Atkins (tuyển dịch)',
                'publisher' => 'NXB Thế giới',
                'year' => 2017,
                'isbn' => '978-604-6015-56-2',
                'lang' => 'vi',
                'pages' => 560,
                'tags' => $tags(['database', 'algorithm', 'machine-learning', 'ai']),
            ],
            [
                'category_id' => $cat('Hóa học'),
                'title' => 'Hóa học môi trường',
                'description' => 'Nguồn ô nhiễm không khí, nước và đất được liên kết với chỉ số quốc gia và tiêu chuẩn WHO cập nhật. Phương pháp mẫu bãi, dòng chảy và ước lượng phát thải khí nhà kính mức tỉnh lỵ. Cán bộ môi trường cấp xã và kỹ sư EHS tại KCN cần ngôn ngữ chung khi báo cáo. Bạn xây ma trận mối nguy, đề xuất biện pháp giảm thiểu khả thi và đọc bảng dữ liệu độc tính cơ bản.',
                'author' => 'Nguyễn Đình Thọ',
                'publisher' => 'NXB Xây dựng',
                'year' => 2021,
                'isbn' => '978-604-6126-67-3',
                'lang' => 'vi',
                'pages' => 296,
                'tags' => $tags(['database', 'algorithm', 'linux', 'security']),
            ],
            [
                'category_id' => $cat('Hóa học'),
                'title' => 'Polyme và vật liệu composite',
                'description' => 'Cấu trúc mạch dài, phương pháp tạo mạng và ứng dụng composite sợi carbon trong hàng không được giới thiệu có hình minh họa cắt lớp. An toàn khi gia công nhựa nhiệt dẻo và phụ gia chống cháy được nhắc rõ ràng. Kỹ sư ô tô nhẹ và đóng gói bền vững cần hiểu trade-off giá — hiệu năng. Sau chương trình, bạn chọn nhựa phù hợp điều kiện nhiệt, đọc datasheet Tg/Tm và đề xuất tái chế hạ cấp.',
                'author' => 'George Odian (tuyển dịch)',
                'publisher' => 'NXB Đại học Quốc gia TP. HCM',
                'year' => 2020,
                'isbn' => '978-604-6237-78-4',
                'lang' => 'vi',
                'pages' => 448,
                'tags' => $tags(['database', 'algorithm', 'docker', 'linux']),
            ],
            [
                'category_id' => $cat('Hóa học'),
                'title' => 'Hóa vô cơ tổng hợp',
                'description' => 'Phức kim loại, hóa học pha rắn và catalysis thể rắn ở mức giới thiệu cho phòng lab nghiên cứu nhỏ. Ví dụ tổng hợp nanoparticle kim loại và oxide phục vụ thí nghiệm từ khí đơn giản. Thạc sĩ hóa vô cơ mới vào lab đại học cần chuẩn bị thao tác Schlenk cơ bản. Bạn đọc được article methodology ngắn, thiết kế quy trình tinh thể chậm và ghi nhật ký an toàn hóa chất độc.',
                'author' => 'R. H. Holm (tuyển chương bản dịch)',
                'publisher' => 'NXB Khoa học Tự nhiên và Công nghệ',
                'year' => 2018,
                'isbn' => '978-604-6348-89-5',
                'lang' => 'vi',
                'pages' => 360,
                'tags' => $tags(['database', 'algorithm', 'security', 'linux']),
            ],

            // —— Tiểu thuyết (6) ——
            [
                'category_id' => $cat('Tiểu thuyết'),
                'title' => 'Những người khốn khổ — Victor Hugo',
                'description' => 'Câu chuyện về Jean Valjean và xã hội Pháp thế kỷ XIX lay động nhờ chi tiết nhân đạo và phản ánh bất công giai cấp. Bản dịch đầy đủ giữ giọng văn tráng lệ thích hợp độc giả trưởng thành. Người yêu văn học Pháp và sinh viên ngữ văn muốn đọc tác phẩm mạch nhân vật dày sẽ kiên nhẫn theo dõi. Sau khi đọc, bạn trao đổi được chủ đề tội — phạt — giáo dục và so sánh các thời kỳ lịch sử qua góc nhìn nhân vật.',
                'author' => 'Victor Hugo (dịch giả: Nguyễn Hiến Lê)',
                'publisher' => 'NXB Văn học',
                'year' => 2018,
                'isbn' => '978-604-6459-90-6',
                'lang' => 'vi',
                'pages' => 1488,
                'tags' => $tags(['english', 'marketing', 'web', 'database']),
            ],
            [
                'category_id' => $cat('Tiểu thuyết'),
                'title' => 'Kiêu hãnh và định kiến — Jane Austen',
                'description' => 'Xung đột giữa Elizabeth Bennet và Mr Darcy phản ánh định kiến giai cấp và giới trong nông thôn Anh. Ngôn ngữ hội thoại tinh tế giúp học tiếng Anh qua văn học mà không nhàm chán. Độc giả nữ trẻ và câu lạc bộ sách thường chọn tiểu thuyết này cho phiên thảo luận tình cảm — xã hội. Bạn rút ra được cách Austen dựng twist từ hiểu lầm nhỏ và quan sát khách quan về hôn nhân thời Regency.',
                'author' => 'Jane Austen (bản dịch song ngữ chú thích)',
                'publisher' => 'NXB Trẻ',
                'year' => 2019,
                'isbn' => '978-604-6560-01-7',
                'lang' => 'en',
                'pages' => 432,
                'tags' => $tags(['english', 'marketing', 'ielts', 'web']),
            ],
            [
                'category_id' => $cat('Tiểu thuyết'),
                'title' => 'Không gia đình — Hector Malot',
                'description' => 'Hành trình của Rémi mồ côi lang thang cùng đoàn xiếc thú chạm đến tình người và lòng nhân ái giữa khó khăn. Giọng kể phù hợp thiếu nhi trung học và phụ huynh đọc cùng con hiểu thế giới rộng mở hơn. Giáo viên Ngữ văn cấp hai tìm tài liệu bồi dưỡng nhân cách qua tiểu thuyết cổ điển. Sau khi đọc, bạn phân tích được các biến cố khiến nhân trưởng thành và liên hệ với phong trào bảo vệ trẻ em hiện đại.',
                'author' => 'Hector Malot (dịch: Bùi Phụng)',
                'publisher' => 'NXB Kim Đồng',
                'year' => 2017,
                'isbn' => '978-604-6671-12-8',
                'lang' => 'vi',
                'pages' => 620,
                'tags' => $tags(['english', 'marketing', 'web', 'mobile']),
            ],
            [
                'category_id' => $cat('Tiểu thuyết'),
                'title' => 'Nhà giả kim — Paulo Coelho',
                'description' => 'Câu chuyện mộng du của chàng chăn cừu Santiago gợi mở về ước mơ cá nhân và chấp nhận thử thách. Văn phong giản dị phù hợp độc giả bận rộn muốn đọc một lượt trong cuối tuần. Nhân viên khởi nghiệp và coach phát triển bản thân thường dùng metaphor chuyến đi để gợi chuyện. Bạn nhận ra được vai trò dấu hiệu nhỏ, chi phí cơ hội khi bỏ cuộc và cách viết diary phản chiếu sau mỗi chương.',
                'author' => 'Paulo Coelho (bản dịch)',
                'publisher' => 'NXB Văn học',
                'year' => 2016,
                'isbn' => '978-604-6782-23-9',
                'lang' => 'vi',
                'pages' => 228,
                'tags' => $tags(['english', 'marketing', 'finance', 'web']),
            ],
            [
                'category_id' => $cat('Tiểu thuyết'),
                'title' => 'Đất rừng phương Nam — Sơn Nam',
                'description' => 'Bức tranh miền Tây Nam Bộ với những mảng đời phiêu bạt, buôn bán và anh hùng nhỏ được kể bằng giọng văn địa phương gần gũi. Sách phù hợp độc giả trong nước muốn hiểu thêm đất và người Nam Bộ qua hư cấu lịch sử. Giáo viên dạy văn miền Nam thường chọn trích đoạn cho học sinh làm văn tả cảnh. Bạn cảm nhận được nhịp sông nước, từ vựng đặc thù và ý thức bảo tồn môi trường rừng tràm.',
                'author' => 'Sơn Nam',
                'publisher' => 'NXB Trẻ',
                'year' => 2015,
                'isbn' => '978-604-6893-34-0',
                'lang' => 'vi',
                'pages' => 352,
                'tags' => $tags(['english', 'marketing', 'web', 'database']),
            ],
            [
                'category_id' => $cat('Tiểu thuyết'),
                'title' => 'Dế Mèn phiêu lưu ký — Tô Hoài',
                'description' => 'Dế Mèn trưởng thành qua từng cuộc gặp trong thế giới côn trùng giàu ẩn dụ xã hội Việt Nam xưa. Ngôn ngữ trong sáng phù hợp thiếu nhi và người lớn ôn lại ký ức tuổi thơ. Thư viện trường tiểu học và phụ huynh ưa thích sách Việt cổ điển thường mua ấn bản minh họa mới. Người đọc học được cách tạo nhân vật loài vật có tính cách riêng và đạo đức nhẹ qua biến cố phiêu lưu.',
                'author' => 'Tô Hoài',
                'publisher' => 'NXB Kim Đồng',
                'year' => 2020,
                'isbn' => '978-604-6904-45-1',
                'lang' => 'vi',
                'pages' => 192,
                'tags' => $tags(['english', 'marketing', 'mobile', 'web']),
            ],

            // —— Thơ (6) ——
            [
                'category_id' => $cat('Thơ'),
                'title' => 'Tuyển tập thơ Xuân Quỳnh',
                'description' => 'Những dòng thơ say sưa, nồng nàn và mạnh mẽ phản ánh tiếng nói nữ giới Việt Nam giữa thế kỷ hai mươi. Chú thích chọn lọc giúp độc giả trẻ đặt tác phẩm trong bối cảnh lịch sử văn học. Sinh viên ngữ văn và câu lạc bộ thơ trường đại học tìm nguồn diễn ngâm công phu. Sau khi đọc, bạn phân tích hình ảnh và nhịp thơ tự do, so sánh với Lưu Quang Vũ cùng thời.',
                'author' => 'Xuân Quỳnh',
                'publisher' => 'NXB Văn học',
                'year' => 2019,
                'isbn' => '978-604-7015-56-2',
                'lang' => 'vi',
                'pages' => 280,
                'tags' => $tags(['english', 'marketing', 'web', 'ielts']),
            ],
            [
                'category_id' => $cat('Thơ'),
                'title' => 'Nguyễn Du và Truyện Kiều — nghiên cứu chọn lọc',
                'description' => 'Thể lục bát, điển cố Trung Hoa và chiến lược dịch nghĩa trong Kiều được phân tích có trích dẫn song song. Phần hậu cận đại đặt câu hỏi đọc lại Kiều trong giáo dục phổ thông hiện nay. Giảng viên đại học và học sinh giỏi văn thi HSG quốc gia cần tài liệu tham khảo gọn. Bạn viết được bài luận so sánh nhân vật, bảo vệ luận điểm về nỗi đau phụ nữ phong kiến.',
                'author' => 'PGS.TS. Nguyễn Văn Hoàn',
                'publisher' => 'NXB Đại học Quốc gia Hà Nội',
                'year' => 2018,
                'isbn' => '978-604-7126-67-3',
                'lang' => 'vi',
                'pages' => 340,
                'tags' => $tags(['english', 'ielts', 'database', 'web']),
            ],
            [
                'category_id' => $cat('Thơ'),
                'title' => 'Nhật ký trong tù — Hồ Chí Minh: Thi pháp và ý nghĩa',
                'description' => 'Hình thức thơ lục bát, song thất lục bát trong hoàn cảnh lao tù được phân tích như sự kiên cường tinh thần. Giáo án gợi ý giúp giáo viên phổ thông dạy kết hợp lịch sử và mỹ học. Học sinh THPT và đoàn thể thanh niên tìm hiểu di sản Chủ tịch Hồ Chí Minh qua văn chương. Người đọc diễn giải được layer chính trị — nhân văn song hành trong từng câu thơ ngắn.',
                'author' => 'Hồ Chí Minh (chú giải: Ban biên tập)',
                'publisher' => 'NXB Chính trị quốc gia Sự thật',
                'year' => 2021,
                'isbn' => '978-604-7237-78-4',
                'lang' => 'vi',
                'pages' => 220,
                'tags' => $tags(['english', 'marketing', 'web', 'security']),
            ],
            [
                'category_id' => $cat('Thơ'),
                'title' => 'The Sonnets of William Shakespeare — A Bilingual Study Edition',
                'description' => 'One hundred fifty-four sonnets appear with modern English glosses and brief notes on metaphor clusters about time, love, and patronage. Pairs well with drama courses comparing lyric voice to soliloquy. Advanced secondary students, literature majors, and bilingual readers who prefer side-by-side layout will appreciate the apparatus. Studying the sequence trains close reading, scansion of iambic pentameter, and argumentative essays on ambiguous volta turns.',
                'author' => 'William Shakespeare',
                'publisher' => 'Pelican Shakespeare Companion',
                'year' => 2017,
                'isbn' => '978-604-7348-89-5',
                'lang' => 'en',
                'pages' => 416,
                'tags' => $tags(['english', 'ielts', 'marketing', 'web']),
            ],
            [
                'category_id' => $cat('Thơ'),
                'title' => 'Thơ Hàn Mặc Tử',
                'description' => 'Thiên lãng mạn với hình ảnh biển, trăng và khát sống được tái bản kèm chú thích tác giả và bệnh tật ảnh hưởng sáng tác. Phù hợp độc giả yêu thơ Việt Nam hiện đại đầu thế kỷ hai mươi. Nghiên cứu sinh văn học so sánh trường phái Thơ mới tìm bản in tin cậy. Bạn đọc nhận ra dòng cảm xúc, chủ đề tôn giáo và sự chuyển tông giữa các giai đoạn sớm muộn của nhà thơ.',
                'author' => 'Hàn Mặc Tử',
                'publisher' => 'NXB Văn học',
                'year' => 2016,
                'isbn' => '978-604-7459-90-6',
                'lang' => 'vi',
                'pages' => 180,
                'tags' => $tags(['english', 'marketing', 'web', 'database']),
            ],
            [
                'category_id' => $cat('Thơ'),
                'title' => 'Thơ đương đại Việt Nam — Tuyển tập 2000–2020',
                'description' => 'Các thế hệ nhà thơ sau Đổi mới được giới thiệu qua bài thơ ngắn, thơ trữ tình và thực hành thử nghiệm có giải thích biên tập. Mục phỏng vấn tác giả giúp độc giả hiểu bối cảnh sáng tác đô thị hóa. Sinh viên báo chí — văn và festival thơ trẻ cần snapshot đa dạng giọng điệu. Sau sách, bạn dựng được map xu hướng, chọn 3 tác giả yêu thích và viết review có trích dẫn.',
                'author' => 'Hội Nhà văn Việt Nam (tuyển)',
                'publisher' => 'NXB Hội Nhà văn',
                'year' => 2022,
                'isbn' => '978-604-7560-01-7',
                'lang' => 'vi',
                'pages' => 400,
                'tags' => $tags(['english', 'marketing', 'web', 'mobile']),
            ],

            // —— Phương pháp dạy học (6) ——
            [
                'category_id' => $cat('Phương pháp dạy học'),
                'title' => 'Phương pháp dạy học tích cực ở bậc phổ thông',
                'description' => 'Hoạt động nhóm, khăn trải bàn và flip classroom mô hình hóa theo đơn vị bài 45 phút thực tế. Phần đánh giá formative giúp GV không chỉ chấm điểm mà phản hồi kịp thời. Giáo viên THCS — THPT đang đổi mới theo chương trình 2018 cần ví dụ triển khai cụ thể. Bạn thiết kế được phiếu học tập, rubric quan sát hành vi và kế hoạch điều chỉnh sau từng tiết thử nghiệm.',
                'author' => 'Nguyễn Công Hà',
                'publisher' => 'NXB Đại học Sư phạm',
                'year' => 2020,
                'isbn' => '978-604-7671-12-8',
                'lang' => 'vi',
                'pages' => 312,
                'tags' => $tags(['english', 'marketing', 'web', 'database']),
            ],
            [
                'category_id' => $cat('Phương pháp dạy học'),
                'title' => 'Dạy học theo dự án (Project-Based Learning)',
                'description' => 'Chu kỳ thắc mắc — nghiên cứu — sản phẩm công khai được minh họa qua dự án STEM nước sạch và lịch sử địa phương. Ma trận mapping chuẩn năng lực giúp hiệu trưởng giám sát không làm quá tải giáo viên. Chuyên viên tư vấn chương trình quốc tế và tổ trưởng tổ bộ môn xây timeline phù hợp học kỳ. Học xong, bạn tổ chức được exhibition nhỏ, đánh giá peer và lưu portfolio học sinh.',
                'author' => 'Suzie Boss, Jane Krauss (bản dịch)',
                'publisher' => 'NXB Giáo dục Việt Nam',
                'year' => 2019,
                'isbn' => '978-604-7782-23-9',
                'lang' => 'vi',
                'pages' => 368,
                'tags' => $tags(['english', 'database', 'web', 'mobile']),
            ],
            [
                'category_id' => $cat('Phương pháp dạy học'),
                'title' => 'Flipped Classroom: Lớp học đảo ngược thực hành',
                'description' => 'Video bài giảng ngắn, câu hỏi checkpoint và tiết lớp dành cho workshop thảo luận được lên kịch bản rõ ràng. Cảnh báo về khoảng cách số khi học sinh không có thiết bị ở nhà được nhắc kèm giải pháp offline. Giáo viên dạy trực tuyến — kết hợp và người mới áp dụng EdTech cần checklist an toàn dữ liệu nhẹ. Người học cân bằng được khối lượng soạn video, thu thập log xem và điều chỉnh độ khó khi đến lớp.',
                'author' => 'Jon Bergmann, Aaron Sams (bản dịch)',
                'publisher' => 'NXB Lao động',
                'year' => 2018,
                'isbn' => '978-604-7893-34-0',
                'lang' => 'vi',
                'pages' => 244,
                'tags' => $tags(['web', 'mobile', 'database', 'security']),
            ],
            [
                'category_id' => $cat('Phương pháp dạy học'),
                'title' => 'Đánh giá năng lực trong chương trình GDPT 2018',
                'description' => 'Ma trận đề minh họa theo mức độ nhận biết — thông hiểu — vận dụng gắn với môn cụ thể. Case phối hợp xác nhận tích lũy giữa các lớp tránh đánh giá trùng lặp. Tổ trưởng chuyên môn và hiệu phó chuyên môn cầm sách khi thống nhất ngân hàng câu hỏi trong tổ. Sau khóa, bạn viết được hướng dẫn chấm rubric, tổ chức tập huấn nội bộ ngắn và lưu minh chứng cho kiểm định.',
                'author' => 'Vụ Giáo dục Trung học (tuyển bài phân tích)',
                'publisher' => 'NXB Giáo dục Việt Nam',
                'year' => 2021,
                'isbn' => '978-604-7904-45-1',
                'lang' => 'vi',
                'pages' => 290,
                'tags' => $tags(['database', 'english', 'marketing', 'algorithm']),
            ],
            [
                'category_id' => $cat('Phương pháp dạy học'),
                'title' => 'Ứng dụng công nghệ trong giảng dạy',
                'description' => 'LMS, công cụ bình chọn nhanh và chấm bài tự động một phần giúp giảm công sức hành chính lặp lại. Nguyên tắc bảo mật tài khoản học sinh và chia sẻ tài nguyên mở được viết thành quy ước tổ. Giáo viên trẻ và quản trị phòng máy trường phổ thông muốn tích hợp có trách nhiệm. Bạn chọn được công cụ phù hợp băng thông, thiết lập khóa học mẫu và đánh giá hiệu quả sau 4 tuần pilot.',
                'author' => 'Trần Bảo Toàn',
                'publisher' => 'NXB Thông tin và Truyền thông',
                'year' => 2023,
                'isbn' => '978-604-8015-56-2',
                'lang' => 'vi',
                'pages' => 276,
                'tags' => $tags(['web', 'security', 'database', 'cloud']),
            ],
            [
                'category_id' => $cat('Phương pháp dạy học'),
                'title' => 'Tâm lý học sư phạm đại cương',
                'description' => 'Trí nhớ làm việc, động cơ học tập và đặc điểm tuổi vị thành niên giúp giáo viên giải thích hành vi lớp học đa dạng. Chiến lược quản lý lớp tích cực thay vì trừng phạt duy nhất được minh họa kịch bản. Sinh viên sư phạm năm 1–2 và GV mới vào nghề cần khung lý thuyết — thực hành cân bằng. Người đọc áp dụng được phỏng vấn học sinh sau tiết, nhật ký phản chiếu và hợp tác với phụ huynh hiệu quả hơn.',
                'author' => 'Lâm Anh Tuấn',
                'publisher' => 'NXB Đại học Sư phạm TP. HCM',
                'year' => 2017,
                'isbn' => '978-604-8126-67-3',
                'lang' => 'vi',
                'pages' => 410,
                'tags' => $tags(['english', 'marketing', 'database', 'algorithm']),
            ],

            // —— Đánh giá học tập (6) ——
            [
                'category_id' => $cat('Đánh giá học tập'),
                'title' => 'Đánh giá học tập theo chuẩn và rubric',
                'description' => 'Rubric đa tiêu chí mô tả mức đạt được thiết kế để học sinh tự đối chiếu trước khi nộp. Quy trình moderation giữa hai giáo viên giảm chênh lệch chấm chủ quan. Hiệu trưởng và tổ trưởng khi xây quy chế đánh giá nội bộ cần mẫu văn bản. Bạn biên soạn được rubric môn tự chọn, workshop calibrate điểm và báo cáo cải tiến sau kỳ.',
                'author' => 'Susan M. Brookhart (bản dịch)',
                'publisher' => 'NXB Đại học Huế',
                'year' => 2018,
                'isbn' => '978-604-8237-78-4',
                'lang' => 'vi',
                'pages' => 330,
                'tags' => $tags(['database', 'english', 'marketing', 'algorithm']),
            ],
            [
                'category_id' => $cat('Đánh giá học tập'),
                'title' => 'Đề kiểm tra và ngân hàng câu hỏi hiệu quả',
                'description' => 'Blueprint đề thi, ma trận độ khó và phân tích đáp án nhiễu giúp ngân hàng câu bền vững qua nhiều kỳ. Hướng dẫn pilot câu mới trên mẫu nhỏ trước khi đưa vào kỳ chính thức. Cán bộ khảo thí trường và sở giáo dục cần checklist kỹ thuật in — online. Sau sách, bạn dựng được phiên bản hóa đề, theo dõi chỉ số phân biệt câu và lưu log chỉnh sửa.',
                'author' => 'PGS.TS. Hoàng Thị Minh',
                'publisher' => 'NXB Đại học Sư phạm',
                'year' => 2020,
                'isbn' => '978-604-8348-89-5',
                'lang' => 'vi',
                'pages' => 260,
                'tags' => $tags(['database', 'security', 'web', 'algorithm']),
            ],
            [
                'category_id' => $cat('Đánh giá học tập'),
                'title' => 'Đánh giá định kỳ và đánh giá thường xuyên',
                'description' => 'Cân bằng điểm số hệ số với nhận xét định tính nhằm giảm học tủ và học vẹt cuối kỳ. Lịch nhắc phụ đạo sớm dựa trên điểm checkpoint từng tháng. GVCN và phụ trách điểm trường phục vụ học sinh có hoàn cảnh khó khăn cần quy trình minh bạch. Người học thiết kế báo cáo học tập cha mẹ đọc hiểu, gắn minh chứng portfolio.',
                'author' => 'James H. McMillan (tuyển dịch)',
                'publisher' => 'NXB Giáo dục Việt Nam',
                'year' => 2016,
                'isbn' => '978-604-8459-90-6',
                'lang' => 'vi',
                'pages' => 318,
                'tags' => $tags(['database', 'marketing', 'english', 'web']),
            ],
            [
                'category_id' => $cat('Đánh giá học tập'),
                'title' => 'Measurement and Evaluation in Education',
                'description' => 'Reliability, validity, and standard error of measurement are explained through classroom-sized datasets so instructors see why long tests reduce random error. Item analysis flags confusing distractors before official scoring. Graduate students in education research and assessment coordinators designing licensing exams share the same vocabulary. Working the exercises teaches you to interpret KR-20, construct parallel forms ethically, and communicate limitations to policy makers.',
                'author' => 'W. James Popham',
                'publisher' => 'Pearson',
                'year' => 2017,
                'isbn' => '978-604-8560-01-7',
                'lang' => 'en',
                'pages' => 480,
                'tags' => $tags(['english', 'database', 'algorithm', 'marketing']),
            ],
            [
                'category_id' => $cat('Đánh giá học tập'),
                'title' => 'Phân tích dữ liệu điểm số trong trường học',
                'description' => 'Bảng tính pivot và biểu đồ boxplot mô tả phân phối điểm theo lớp — môn mà không lộ danh tính học sinh. Quy tắc ẩn danh hóa khi chia sẻ báo cáo với ban giám hiệu được nhấn mạnh. Chuyên viên QAQC và thư ký khảo thí muốn tự động hóa nhẹ báo cáo cuối kỳ. Bạn xây dashboard nội bộ, phát hiện bất thường chấm thi và lưu version dữ liệu.',
                'author' => 'Võ Thị Kim Ngân',
                'publisher' => 'NXB Thống kê',
                'year' => 2022,
                'isbn' => '978-604-8671-12-8',
                'lang' => 'vi',
                'pages' => 228,
                'tags' => $tags(['database', 'data-science', 'algorithm', 'web']),
            ],
            [
                'category_id' => $cat('Đánh giá học tập'),
                'title' => 'Assessment for Learning: Phản hồi trong lớp học',
                'description' => 'Câu hỏi mở đầu tiết, thẻ màu và từ khóa đầu cầu nối giúp giáo viên điều chỉnh nội dung ngay lập tức. Nguyên tắc phản hồi cụ thể, đúng thời điểm tránh chung chung gây nản. GV tiểu học và THCS muốn giảm thi cử áp lực duy nhất cuối năm sẽ có công cụ. Hoàn thành, bạn viết được journal sau tiết, thử exit ticket 2 phút và chia sẻ chiến lược học tập hiệu quả cho phụ huynh.',
                'author' => 'Dylan Wiliam (bản dịch)',
                'publisher' => 'NXB Trẻ',
                'year' => 2019,
                'isbn' => '978-604-8782-23-9',
                'lang' => 'vi',
                'pages' => 292,
                'tags' => $tags(['english', 'marketing', 'web', 'database']),
            ],

            // —— Nội khoa (6) ——
            [
                'category_id' => $cat('Nội khoa'),
                'title' => 'Nội khoa học — Bệnh viện Bạch Mai',
                'description' => 'Khám bệnh từ ca điển, chẩn đoán phân biệt và thuật toán xử trí ban đầu được tập hợp theo hệ cơ quan. Ảnh minh họa X-quang, điện tim điển hình phục vụ thực tập lâm sàng năm cuối. Bác sĩ nội trú và điều dưỡng trưởng khoa nội cần tài liệu nhất quán với phác đồ bệnh viện tuyến trung ương. Người đọc lập được mẫu ghi chú lâm sàng, trình bày case ngắn trong buổi seminar lâm sàng và hiểu cơ sở chỉ định cận lâm sàng.',
                'author' => 'Hội đồng biên tập Bệnh viện Bạch Mai',
                'publisher' => 'NXB Y học',
                'year' => 2020,
                'isbn' => '978-604-8893-34-0',
                'lang' => 'vi',
                'pages' => 960,
                'tags' => $tags(['database', 'security', 'ai', 'machine-learning']),
            ],
            [
                'category_id' => $cat('Nội khoa'),
                'title' => 'Tim mạch lâm sàng căn bản',
                'description' => 'Suy tim, rối loạn nhịp và tăng huyết áp được phân tầng nguy cơ theo guideline cập nhật gần nhất. Biểu đồ flowchart điều trị giúp tránh chỉ định thuốc mâu thuẫn. Bác sĩ đa khoa tuyến xã cần nhanh chóng nhận diện red flag cấp cứu. Bạn thực hành được anamnesis có hệ thống, đọc ECG cơ bản và truyền đạt kế hoạch điều trị cho bệnh nhân dễ hiểu.',
                'author' => 'Braunwald (tuyển chương bản dịch)',
                'publisher' => 'NXB Y học',
                'year' => 2018,
                'isbn' => '978-604-8904-45-1',
                'lang' => 'vi',
                'pages' => 520,
                'tags' => $tags(['database', 'ai', 'machine-learning', 'security']),
            ],
            [
                'category_id' => $cat('Nội khoa'),
                'title' => 'Nội tiết và đái tháo đường',
                'description' => 'Chẩn đoán tiền đái tháo đường, typ 1 — 2 và biến chứng mạn được quản lý theo mục tiêu HbA1c cá thể hóa. Ưu nhược điểm các nhóm thuốc mới GLP-1 và SGLT2 được bàn trên bệnh nhân đi kèm bệnh thận. Nội trú khoa nội tiết và BS gia đình cần sổ tay trên bàn công tác. Người học giáo dục bệnh nhân ăn uống, theo dõi hypoglycemia ban đêm và phối hợp đa chuyên khoa.',
                'author' => 'Nguyễn Văn Phước',
                'publisher' => 'NXB Đại học Y Dược TP. HCM',
                'year' => 2021,
                'isbn' => '978-604-9015-56-2',
                'lang' => 'vi',
                'pages' => 380,
                'tags' => $tags(['database', 'security', 'ai', 'machine-learning']),
            ],
            [
                'category_id' => $cat('Nội khoa'),
                'title' => 'Bệnh hô hấp nội khoa',
                'description' => 'Viêm phổi cộng đồng, hen và COPD cấp — mạn với xử trí oxy và kháng sinh hợp lý. Hình ảnh CT minh họa pattern tổn thương giúp phân biệt ban đầu. Bác sĩ cấp cứu và khoa hô hấp bệnh viện tỉnh cần phác đồ thống nhất. Bạn biết khi nào chuyển tuyến, đọc khí máu đơn giản và tránh lạm dụng kháng sinh rộng phổ.',
                'author' => 'Murray & Nadel (tuyển lược dịch)',
                'publisher' => 'NXB Y học',
                'year' => 2019,
                'isbn' => '978-604-9126-67-3',
                'lang' => 'vi',
                'pages' => 440,
                'tags' => $tags(['database', 'machine-learning', 'ai', 'security']),
            ],
            [
                'category_id' => $cat('Nội khoa'),
                'title' => 'Thận và huyết áp: Quản lý toàn diện',
                'description' => 'Suy thận mạn giai đoạn, protein niệu và bệnh thận do tiểu đường được theo dõi theo lịch hẹn và chỉ định sinh thiết chọn lọc. Chiến lược điều trị THA thứ phát sau thận giảm tải lên hệ tuần hoàn. BS trạm y tế và phòng khám chuyên thận cần flowchart rõ ràng. Người đọc tư vấn chế độ muối — nước, điều chỉnh thuốc khi eGFR thay đổi và phối hợp dinh dưỡng lâm sàng.',
                'author' => 'Neil R. Colvin (tuyển dịch)',
                'publisher' => 'NXB Y học',
                'year' => 2017,
                'isbn' => '978-604-9237-78-4',
                'lang' => 'vi',
                'pages' => 360,
                'tags' => $tags(['database', 'security', 'ai', 'algorithm']),
            ],
            [
                'category_id' => $cat('Nội khoa'),
                'title' => 'Tiêu hóa gan mật lâm sàng',
                'description' => 'Vàng da phân tầng, viêm gan virus và xơ gan bù trừ với biến cố giãn tĩnh mạch được quản lý nội khoa — can thiệp nội soi. Guide ăn uống và thuốc giảm amoniac phục vụ gia đình chăm sóc tại nhà an toàn. Bác sĩ nội tiêu hóa và điều dưỡng chuyên khoa gan cần sổ tay đồng nhất hướng dẫn. Bạn nhận diện dấu hiệu xuất huyết tiêu hóa cấp, truyền máu sớm và bàn giao plan follow-up.',
                'author' => 'Sleisenger & Fordtran (tuyển chương Việt hóa)',
                'publisher' => 'NXB Đại học Y Hà Nội',
                'year' => 2022,
                'isbn' => '978-604-9348-89-5',
                'lang' => 'vi',
                'pages' => 510,
                'tags' => $tags(['database', 'machine-learning', 'security', 'ai']),
            ],

            // —— Ngoại khoa (6) ——
            [
                'category_id' => $cat('Ngoại khoa'),
                'title' => 'Ngoại khoa lâm sàng tổng hợp',
                'description' => 'Đau bụng cấp, tắc ruột và chấn thương bụng hở được đánh giá FAST siêu âm sơ bộ rồi quyết định phẫu thuật. Quy trình checklist trước mổ WHO giảm sai sót tầm thường nhưng chí mạng. Bác sĩ cấp cứu và ngoại trú cần thuật ngữ thống nhất khi bàn giao. Người học lập được kịch bản consent, chuẩn bị kháng sinh dự phòng và theo dõi hậu phẫu đa bệnh.',
                'author' => 'Sabiston (tuyển lược bản dịch)',
                'publisher' => 'NXB Y học',
                'year' => 2018,
                'isbn' => '978-604-9459-90-6',
                'lang' => 'vi',
                'pages' => 780,
                'tags' => $tags(['database', 'security', 'algorithm', 'ai']),
            ],
            [
                'category_id' => $cat('Ngoại khoa'),
                'title' => 'Phẫu thuật tiêu hóa căn bản',
                'description' => 'Cắt ruột thừa, thoát vị bẹn và polyp đại tràng phục vụ ngoại trú chọn lọc được trình bày step-by-step hình ảnh. Phần giảm nhiễm khuẩn vết mổ và dẫn lưu phù hợp tránh lạm dụng. Bác sĩ nội trú ngoại sắp vào ca mổ đầu tay cần checklist an toàn. Bạn đọc được chỉ định nội soi versus mổ mở, ước lượng nguy cơ tim mạch trước mê.',
                'author' => 'Đặng Hanh Phúc',
                'publisher' => 'NXB Đại học Y Dược Huế',
                'year' => 2019,
                'isbn' => '978-604-9560-01-7',
                'lang' => 'vi',
                'pages' => 420,
                'tags' => $tags(['database', 'security', 'machine-learning', 'ai']),
            ],
            [
                'category_id' => $cat('Ngoại khoa'),
                'title' => 'Chấn thương chỉnh hình cấp cứu',
                'description' => 'Nạn nhân đa chấn thương: cố định cột sống, xử lý xuất huyết ngoại vi và trật khớp cấp theo ATLS cập nhật. Hướng dẫn bó bột an toàn tránh tổn thương mạch thần kinh kèm hình. BS trực cấp cứu và kỹ thuật viên vận chuyển 115 cần thao tác đồng bộ. Sau khóa, bạn phân loại nạn nhân, ưu tiên can thiệp và ghi báo cáo pháp y đầy đủ khi cần.',
                'author' => 'Rockwood & Green (tuyển chương dịch)',
                'publisher' => 'NXB Y học',
                'year' => 2020,
                'isbn' => '978-604-9671-12-8',
                'lang' => 'vi',
                'pages' => 560,
                'tags' => $tags(['database', 'security', 'algorithm', 'linux']),
            ],
            [
                'category_id' => $cat('Ngoại khoa'),
                'title' => 'Phẫu thuật nội soi ổ bụng',
                'description' => 'Thiết lập khí pneumoperitoneum, vị trí trocar và xử lý tổn thương mạch nhỏ bằng nội soi được mô tả rõ ràng. So sánh chi phí — lợi ích với mổ mở cho từng bệnh lý phổ biến. Phẫu thuật viên nội soi mới độc lập cần video thao tác chậm. Người học chọn case phù hợp learning curve, chuyển sang mổ mở khi chỉ số an toàn vượt ngưỡng và debriefing sau ca.',
                'author' => 'Trần Hùng Chiến',
                'publisher' => 'NXB Y học',
                'year' => 2021,
                'isbn' => '978-604-9782-23-9',
                'lang' => 'vi',
                'pages' => 340,
                'tags' => $tags(['database', 'security', 'docker', 'devops']),
            ],
            [
                'category_id' => $cat('Ngoại khoa'),
                'title' => 'Gây mê hồi sức cho kíp mổ',
                'description' => 'Đánh giá ASA, chọn thuốc mê toàn thân — cục bộ và theo dõi huyết động trong mổ lớn. Protocol team brief trước khi knife time giúp tránh nhầm bệnh nhân. Bác sĩ gây mê và điều dưỡng phòng mổ cần ngôn ngữ chung. Bạn đọc chart gây mê, xử lý tăng CO2 và phối hợp extubation an toàn tại phòng hồi tỉnh.',
                'author' => 'Miller (tuyển lược bản dịch)',
                'publisher' => 'NXB Đại học Y Hà Nội',
                'year' => 2017,
                'isbn' => '978-604-9893-34-0',
                'lang' => 'vi',
                'pages' => 620,
                'tags' => $tags(['database', 'security', 'algorithm', 'ai']),
            ],
            [
                'category_id' => $cat('Ngoại khoa'),
                'title' => 'Vô khuẩn và kỹ thuật phòng mổ',
                'description' => 'Chuẩn bị dụng cụ STERRAD, kiểm soát vòng lưu chuyển nhân viên và vệ sinh tay theo WHO nâng cao. Audit nhiễm khuẩu vết mổ cho phép so sánh tuyến bệnh viện. Kỹ thuật viên vô khuẩn và điều dưỡng trưởng phòng mổ cầm bộ tiêu chuẩn kiểm tra. Người học viết checklist đóng gói dụng cụ, truy vết lot và phản ứng khi phát hiện sai sót dụng cụ.',
                'author' => 'Janice A. McCoy (tuyển dịch)',
                'publisher' => 'NXB Y học',
                'year' => 2022,
                'isbn' => '978-604-9904-45-1',
                'lang' => 'vi',
                'pages' => 268,
                'tags' => $tags(['database', 'security', 'linux', 'docker']),
            ],

            // —— Luật dân sự (6) ——
            [
                'category_id' => $cat('Luật dân sự'),
                'title' => 'Luật dân sự Việt Nam — Bộ luật và áp dụng',
                'description' => 'Cấu trúc Bộ luật Dân sự 2015 được phân mục theo chủ thể, pháp nhân, giao dịch và thời hiệu khởi kiện. Ví dụ án lệ minh họa giúp luật sư mới và sinh viên luật năm 2 hình dung áp dụng thực tiễn. Doanh nghiệp SME cần hiểu khung để soạn hợp đồng lao động — dịch vụ. Sau khi đọc, bạn trích dẫn điều khoản chính xác, viết văn bản đề nghị uy quyền và phác thảo chiến lược tranh tụng sơ bộ.',
                'author' => 'PGS.TS. Doãn Vĩnh Thọ',
                'publisher' => 'NXB Công lý',
                'year' => 2021,
                'isbn' => '978-604-0015-56-2',
                'lang' => 'vi',
                'pages' => 640,
                'tags' => $tags(['database', 'security', 'finance', 'marketing']),
            ],
            [
                'category_id' => $cat('Luật dân sự'),
                'title' => 'Hợp đồng dân sự: Soạn thảo và tranh chấp',
                'description' => 'Điều khoản trọng yếu, điều kiện giao dịch và bất khả kháng trong hợp đồng thương mại dân sự được phân tích có mẫu. Chiến lược hòa giải trước tranh chấp giúp tiết kiệm chi phí tòa. Startup ký hợp đồng với freelance và luật sư tư vấn hợp đồng nội bộ sẽ dùng thực hành này. Bạn soạn phụ lục rủi ro, checklist chữ ký số và lưu version hợp đồng theo audit.',
                'author' => 'Lê Minh Tuấn',
                'publisher' => 'NXB Tài chính',
                'year' => 2019,
                'isbn' => '978-604-0126-67-3',
                'lang' => 'vi',
                'pages' => 380,
                'tags' => $tags(['finance', 'blockchain', 'security', 'database']),
            ],
            [
                'category_id' => $cat('Luật dân sự'),
                'title' => 'Quyền sở hữu và quyền sử dụng đất',
                'description' => 'Sổ đỏ, chuyển nhượng hợp pháp và các loại đất phi nông nghiệp được giải thích qua sơ đồ quy trình công chứng. Cảnh báo mua bán giấy tay và tài sản đính kèm trên đất giúp tránh tranh chấp kéo dài. Công chứng viên và môi giới bất động sản cần thống nhất tư vấn pháp lý. Người học kiểm tra tình trạng thế chấp, đọc quy hoạch chi tiết và lập hồ sơ xin cấp giấy chứng nhận bổ sung.',
                'author' => 'TS. Trần Thanh Thủy',
                'publisher' => 'NXB Đại học Luật Hà Nội',
                'year' => 2020,
                'isbn' => '978-604-0237-78-4',
                'lang' => 'vi',
                'pages' => 330,
                'tags' => $tags(['finance', 'security', 'database', 'marketing']),
            ],
            [
                'category_id' => $cat('Luật dân sự'),
                'title' => 'Thừa kế và di chúc theo pháp luật Việt Nam',
                'description' => 'Di chúc hợp pháp, thừa kế theo pháp luật và quyền được hưởng thừa kế của người phụ thuộc được phân tích trên tình huống gia đình đa thế hệ. Mẫu văn bản di chúc và từ chối di sản minh họa rõ ràng. Luật sư hành nghề hộ gia đình và cán bộ tư pháp cơ sở cần văn bản dễ tra cứu. Sau sách, bạn tư vấn phân chia di sản, hòa giải anh em và chuẩn bị hồ sơ khai nhận di sản.',
                'author' => 'Nguyễn Thị Thu Hà',
                'publisher' => 'NXB Dân chủ',
                'year' => 2018,
                'isbn' => '978-604-0348-89-5',
                'lang' => 'vi',
                'pages' => 280,
                'tags' => $tags(['finance', 'security', 'database', 'marketing']),
            ],
            [
                'category_id' => $cat('Luật dân sự'),
                'title' => 'Bồi thường thiệt hại ngoài hợp đồng',
                'description' => 'Cấu thành lỗi, thiệt hại thực tế và mối quan hệ nhân quả trong từng nhóm vụ cố ý — vô ý. Án lệ từ tai nạn giao thông và sản phẩm lỗi được tóm tắt có trích luật. Luật sư tranh tụng dân sự và bảo hiểm bồi thường trách nhiệm dùng làm tài liệu nội bộ. Bạn lập được tính toán dự phòng bồi thường, thương lượng ngoài tòa và chuẩn bị chứng cứ chuyên môn.',
                'author' => 'Đỗ Văn Đại',
                'publisher' => 'NXB Công lý',
                'year' => 2022,
                'isbn' => '978-604-0459-90-6',
                'lang' => 'vi',
                'pages' => 360,
                'tags' => $tags(['finance', 'security', 'database', 'algorithm']),
            ],
            [
                'category_id' => $cat('Luật dân sự'),
                'title' => 'Hôn nhân và gia đình — Điều chỉnh pháp lý',
                'description' => 'Điều kiện kết hôn, thỏa thuận tài sản chung — riêng và quyền nuôi con sau ly hôn được giải thích bằng sơ đồ luồng thủ tục. Hướng dẫn hòa giải tại tòa trước khi mở phiên xét xử. Thẩm phán sơ thẩm và tư vấn pháp lý trợ giúp phụ nữ cần ngôn ngữ nhất quán. Người đọc hoàn thiện đơn khởi kiện, chuẩn bị bảo vệ quyền trẻ em và phối hợp công chứng viên.',
                'author' => 'Bùi Thị Thu Thủy',
                'publisher' => 'NXB Hồng Đức',
                'year' => 2023,
                'isbn' => '978-604-0560-01-7',
                'lang' => 'vi',
                'pages' => 310,
                'tags' => $tags(['security', 'finance', 'database', 'marketing']),
            ],

            // —— Luật kinh doanh (6) ——
            [
                'category_id' => $cat('Luật kinh doanh'),
                'title' => 'Luật doanh nghiệp Việt Nam',
                'description' => 'Công ty TNHH, cổ phần và hợp danh được so sánh về góp vốn, phân phối lợi nhuận và trách nhiệm pháp lý. Quy trình đăng ký kinh doanh online và thay đổi giấy phép được minh họa theo bước. Nhà đầu tư cá nhân và kế toán trưởng DN vừa và nhỏ cần bản đồ pháp lý cập nhật. Sau khóa, bạn đọc được điều lệ mẫu, tránh lỗi chữ ký đại diện và lập nghị quyết đại hội đồng cổ đông sơ bộ.',
                'author' => 'TS. Phạm Nhật Minh',
                'publisher' => 'NXB Thương mại',
                'year' => 2021,
                'isbn' => '978-604-0671-12-8',
                'lang' => 'vi',
                'pages' => 420,
                'tags' => $tags(['finance', 'blockchain', 'security', 'database']),
            ],
            [
                'category_id' => $cat('Luật kinh doanh'),
                'title' => 'Pháp luật chứng khoán và thị trường vốn',
                'description' => 'Chào bán riêng lẻ, IPO và công bố thông tin định kỳ được phân tích trên khung UBCKNN hiện hành. Case vi phạm giao dịch nội bộ minh họa mức phạt và biện pháp khắc phục. Luật sư công ty niêm yết và chuyên viên tuân thủ cầm sách khi rà compliance. Bạn theo dõi được nghĩa vụ công bố, lập hồ sơ chào bán trái phiếu doanh nghiệp và tư vấn hội đồng quản trị.',
                'author' => 'Lê Hoàng Yến',
                'publisher' => 'NXB Tài chính',
                'year' => 2020,
                'isbn' => '978-604-0782-23-9',
                'lang' => 'vi',
                'pages' => 480,
                'tags' => $tags(['finance', 'blockchain', 'security', 'marketing']),
            ],
            [
                'category_id' => $cat('Luật kinh doanh'),
                'title' => 'Luật cạnh tranh và bảo vệ người tiêu dùng',
                'description' => 'Hành vi lạm dụng vị trí thống lĩnh, thỏa thuận hạn chế cạnh tranh và quảng cáo sai lệch bị xử lý thế nào trong điều tra hành chính. Quy trình khiếu nại người tiêu dùng tại Hiệp hội và cơ quan nhà nước được liệt kê địa chỉ. Chuyên viên pháp chế hãng bán lẻ và startup platform cần phòng ngừa rủi ro. Người học soạn điều khoản công bằng, xây chính sách hoàn tiền và phối hợp truyền thông khủng hoảng.',
                'author' => 'Nguyễn Tiến Đức',
                'publisher' => 'NXB Chính trị quốc gia Sự thật',
                'year' => 2019,
                'isbn' => '978-604-0893-34-0',
                'lang' => 'vi',
                'pages' => 340,
                'tags' => $tags(['finance', 'marketing', 'security', 'database']),
            ],
            [
                'category_id' => $cat('Luật kinh doanh'),
                'title' => 'Đầu tư nước ngoài và pháp lý liên quan',
                'description' => 'Hình thức liên doanh, 100% vốn nước ngoài và ưu đãi ngành công nghệ cao được đặt song song bảng cam kết WTO liên quan. Thủ tục giấy phép đầu tư và báo cáo định kỳ giúp tránh cắt giảm ưu đãi do sai sót. Luật sư đầu tư và phòng đầu tư KCN cần tư liệu cập nhật Luật Đầu tư sửa đổi. Bạn đọc được NĐ hướng dẫn, hoàn thiện hồ sơ thẩm định môi trường và tranh tụng hợp đồng FDI sơ bộ.',
                'author' => 'Võ Thị Lan Anh',
                'publisher' => 'NXB Pháp lý',
                'year' => 2022,
                'isbn' => '978-604-0904-45-1',
                'lang' => 'vi',
                'pages' => 390,
                'tags' => $tags(['finance', 'blockchain', 'security', 'cloud']),
            ],
            [
                'category_id' => $cat('Luật kinh doanh'),
                'title' => 'Sở hữu trí tuệ trong kinh doanh',
                'description' => 'Nhãn hiệu, sáng chế và bản quyền phần mềm được đăng ký và thực thi tại Việt Nam và WIPO cơ bản. Chiến lược due diligence khi M&A startup công nghệ tránh rủi ro license. Luật sư IP và trưởng phòng R&D doanh nghiệp cần checklist nội bộ. Người đọc soạn hợp đồng chuyển giao công nghệ, theo dõi thời hạn gia hạn patent và xử lý vi phạm online.',
                'author' => 'Lưu Anh Tuấn',
                'publisher' => 'NXB Khoa học và Kỹ thuật',
                'year' => 2021,
                'isbn' => '978-604-1015-56-2',
                'lang' => 'vi',
                'pages' => 360,
                'tags' => $tags(['blockchain', 'security', 'database', 'finance']),
            ],
            [
                'category_id' => $cat('Luật kinh doanh'),
                'title' => 'Trọng tài thương mại và giải quyết tranh chấp',
                'description' => 'Điều khoản trọng tài trong hợp đồng FIDIC và B2B xuất khẩu giúp tránh tố tụng kéo dài tại tòa án. Quy trình chọn trọng tài viên, thu thập chứng cứ và thi hành phán quyết được mô tả theo Luật Trọng tài. Luật sư tranh tụng thương mại và giám đốc pháp chế tập đoàn cần sổ tay xử lý. Bạn soạn thư mời khởi kiện trọng tài, ước tính chi phí và phối hợp luật sư nước ngoài khi đa jurisdictions.',
                'author' => 'Hoàng Nam Tiến',
                'publisher' => 'NXB Công lý',
                'year' => 2023,
                'isbn' => '978-604-1126-67-3',
                'lang' => 'vi',
                'pages' => 318,
                'tags' => $tags(['finance', 'security', 'database', 'blockchain']),
            ],
        ];

        foreach ($documents as $i => $data) {
            $doc = Document::create([
                'category_id' => $data['category_id'],
                'uploaded_by' => $adminId,
                'title' => $data['title'],
                'slug' => Str::slug($data['title']).'-'.$i,
                'description' => $data['description'],
                'author' => $data['author'],
                'publisher' => $data['publisher'],
                'published_year' => $data['year'],
                'isbn' => $data['isbn'] ?? null,
                'language' => $data['lang'],
                'pages' => $data['pages'],
                'file_url' => 'documents/sample.pdf',
                'cover_image' => $coverImage,
                'view_count' => rand(0, 2000),
                'download_count' => rand(0, 500),
                'is_featured' => $i < 10,
            ]);

            $doc->tags()->sync($data['tags']);
        }
    }
}
